### ISSUE TITLE
Fix makefile in docs section

### ISSUE THREAD

**Issue by sumit4613** [101Loop/drf-user#117]
### Description of the bug

While running sphinx-build to  create HTML pages, it asks for a source dir now.

Just put `$(SOURCEDIR)` in `$(SPHINXBUILD) -b html $(ALLSPHINXOPTS) $(BUILDDIR)/html` after `$(ALLSPHINXOPTS)`. This will fix the issue. Try to run `make html` first to check if it's working or not.

**Comment by sumit4613** [comment]
Same should be done for `linkcheck`.

**Comment by aayush-jaiswal** [comment]
I will work on this
