### ISSUE TITLE
Pin all dependencies in requirements-dev.txt.

### ISSUE THREAD

**Issue by inovizz** [101Loop/drf-user#120]
### Environment
- `drf-user` version(s) (`drf-user --version`: 3.12.4
- Operating System(s): Mac
- Python version(s): 3.9.7

### Description of the bug
pin dependencies in requirements-dev.txt.

### What you expected to happen
pin dependencies, run commands and see everything runs fine.

### How to reproduce (as minimally and precisely as possible)
NA

### Anything else we need to know?
NA

**Comment by iamhssingh** [comment]
@inovizz Are you working on this one?
