### ISSUE TITLE
Make file execution failing for windows.

### ISSUE THREAD

**Issue by NaveenGokavarapu19** [101Loop/drf-user#123]
### Environment

- `drf-user` version(s) (`drf-user --version`:
- Operating System(s): Windows
- Python version(s): 3.8

### Description of the bug

Make install is working but make test and livehtml is not working.

### What you expected to happen

Tests passing and html page constructed.

### How to reproduce (as minimally and precisely as possible)

After cloning repo and install make using choco and run the make files getting this error

```
make test
${VIRTUAL_ENV-.venv}/bin/python -m pytest --disable-pytest-warnings --ds=tests.settings --cov=drf_user tests/
process_begin: CreateProcess(NULL, ${VIRTUAL_ENV-.venv}/bin/python -m pytest --disable-pytest-warnings --ds=tests.settings --cov=drf_user tests/, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [Makefile:67: test] Error 2
```

**Comment by NaveenGokavarapu19** [comment]
Run this command where.exe python in windows to get python interpreter path.

C:\Users\<User>\<venv-name>\env\Scripts\python.exe
C:\Users\<User>\AppData\Local\Microsoft\WindowsApps\python.exe

The first path is python interpreter path.

**Comment by NaveenGokavarapu19** [comment]
Run this command in powershell in admin to install make in windows

choco install make

**Comment by gauravp446** [comment]
Hi @sumit4613 please merge this PR #128

**Comment by sumit4613** [comment]
Hey, @gauravp446 really sorry man, for not merging this before.  Got busy at work. Merging it right away.

**Comment by gauravp446** [comment]
Thanks @sumit4613
