### ISSUE TITLE
OTP functionality not working.

### ISSUE THREAD

**Issue by niteshrawat1995** [101Loop/drf-user#3]
Hi Himanshu,
Couple of days earlier I implemented the drf_user for my personal project. But not able to receive an OTP code for verification. I tried to look for the solution on my own but cannot find it. Have you seen such issue in the past? Please suggest a fix. Thanks in advance.

**Comment by iamhssingh** [comment]
Please share error message that you got?

**Comment by iamvivekkaushik** [comment]
I found the error, there seems to be a weird bug when otp starts with 0, the `serializer.validated_data.get('verify_otp', None)` on line 308 in `views.py` removes the 0 from the otp which in turns fails the verification process.
