### ISSUE TITLE
Update contribution guide

### ISSUE THREAD

**Issue by sumit4613** [101Loop/drf-user#58]
### Describe the feature you'd like

We need to update the contribution guide to tell new contributors on how to work with forked copy of this repo.

**Comment by Arnau-Ninerola** [comment]
I would like to work on this, but I see the contribution guide pretty complete. What would you like to add?

**Comment by sumit4613** [comment]
@Arnau-Ninerola I have described it already in the issue itself, we need to add details about how to work with forked copy of this repo.
