### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by sumit4613** [101Loop/drf-user#59]
### Describe the feature you'd like

Update README.md to include tools that we are using for PEP8 compliance, CI and all.
Please ping me, if you want to work on it.

**Comment by lkdmttg7** [comment]
Hi. I would like to work on this.

**Comment by sumit4613** [comment]
@lkdmttg7 If you still wanna work on this please let me know. Will let you know what needs to be updated.

**Comment by lkdmttg7** [comment]
Yes, sure
