### ISSUE TITLE
PyPI sdist failure

### ISSUE THREAD

**Issue by jayvdb** [101Loop/drf-user#6]
```py
Traceback (most recent call last):
  File "setup.py", line 19, in <module>
    install_requires=open('requirements.txt').read().split(),
FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by sumit4613** [comment]
@jayvdb can you tell how can I reproduce this error? Sorry for replying late as this project wasn't very active lately.

**Comment by jayvdb** [comment]
Unpack https://files.pythonhosted.org/packages/bb/5e/499f84174fd77077abbc62efae0d83342361986aaefa391fa19232e46f5c/drf_user-0.0.8.tar.gz , and run `python3 setup.py build` or `.. install`

`MANIFEST.in` must contain any file mentioned in `setup.py` .

https://pypi.org/project/check-manifest/ is a great tool to ensure files are not accidentally forgotten.

**Comment by sumit4613** [comment]
@jayvdb I have added/updated `MANIFEST.in`. This will be updated in the next release of the package. Thanks for reporting this.

If you face any other errors, please create issue for them.

Thanks!

**Comment by jayvdb** [comment]
It would be great if you could tag 0.0.8 at https://github.com/101Loop/drf-user/releases so I can fetch that version and test it

**Comment by sumit4613** [comment]
@jayvdb I have added a pre-release for v0.0.8. Please test it out and let us know if you face any errors.

I'm closing this issue now, if you feel there's some issue with `MANIFEST.in` please open this issue again. :smile:
