### ISSUE TITLE
Figure out a way to export API endpoints of drf-user in open-api format 

### ISSUE THREAD

**Issue by sumit4613** [101Loop/drf-user#60]
### Describe the feature you'd like

We need an option in documentation to export API endpoints in [Openapi](https://swagger.io/specification/) format, so that a user can easily download all the API endpoints in openapi format and then APIs can be easily tested with [postman](https://www.postman.com/) or some other tool.

**Comment by sumit4613** [comment]
We will add a demo project and use drf-yasg to expose endpoints of drf-user. Then users will be able to download all endpoints in OpenAPI format.

**Comment by iamvivekkaushik** [comment]
You can do this with from the redoc, with drf-yasg package.

**Comment by sumit4613** [comment]
@iamvivekkaushik yep I know, we'll be adding this in demo app, so that user can easily checkout endpoints

**Comment by sumit4613** [comment]
Merged #86 

Now APIs can be exported using swagger.
