### ISSUE TITLE
Add Payment integration

### ISSUE THREAD

**Issue by antriksh123** [101Loop/drf-user#66]
### Describe the feature you'd like
A payment integration is really vital for ecommerce web applications with payment integration.

### Is your feature request related to a problem?
No, it is not related to any problem.

**Comment by sumit4613** [comment]
@antriksh123 Well yeah payment integration is a vital feature for web applications, but payment integration isn't relevant to our project. 
We have other projects for that feature. Please checkout [drf-instamojo](https://github.com/101loop/drf-instamojo) and [drf-paytm](https://github.com/101loop/drf-paytm/)

So, I'm closing this issue. 
Thanks!
