### ISSUE TITLE
Add webhook

### ISSUE THREAD

**Issue by alainseys** [101Loop/drf-user#67]
A realy nice feature should be the applility to add a webhook so you can connect the app trough (like Teams, Slack ...).
You can use the webhooks0.4.2 package to complete this feature request.

**Comment by sumit4613** [comment]
@alainseys Would you like to tell us, how a webhook is relevant to our project??

**Comment by alainseys** [comment]
Wel instead of send email as registration you send it trough eg teams or so. 

And if you have any communication to the user you can send those messages also by that way.

**Comment by sumit4613** [comment]
@alainseys I don't think we need webhook feature yet, in future maybe yes. If you want to work on this issue please let me know. I'll be closing this issue for now.
Thanks for your interest in drf-user btw.

**Comment by alainseys** [comment]
When this is needed I can work on it

**Comment by sumit4613** [comment]
@alainseys I don't know when this feature will be required, but if you want you can work on it. Would love to review your PR.
