### ISSUE TITLE
Makefile port command issue

### ISSUE THREAD

**Issue by HardipinderS** [101Loop/drf-user#68]
### Environment

- `drf-user` version(s) (`drf-user --version`: git fork
- Operating System(s): Windows 10
- Python version(s): 3.7.7

### Description of the bug
Makefile not working while running make livehtml and update on the docs for windows user

### What you expected to happen
removing -p as it is not working. Rather having it run directly as addition of --open-browser and --port fixes that 

### How to reproduce (as minimally and precisely as possible)
running the latest build

### Anything else we need to know?
FYI: Sphinx is planning to move away from using Makefile as mentioned in sphinx autobuild documentation

**Comment by HardipinderS** [comment]
pushed latest commit to docs branch, please check

**Comment by sumit4613** [comment]
@HardipinderS can you share some screenshots about what's the error you're getting. and btw how you're running Makefile in windows?

**Comment by HardipinderS** [comment]
I'm sorry but I didn't keep screen shots while getting the error. 

Error was with `sphinx-autobuild`. as the command `livehtml `was not able to run as it had `-p` as the in it. The moment I removed `-p` and `--port` it worked. Added `--open-browser` option to open the docs in browser.

ran `make `using `chocolatey`. 

I've added this to the contribution.md file.

**Comment by sumit4613** [comment]
@HardipinderS you haven't raised a PR yet, please raise a PR from your repo to 101loop's repo. Then i'll review your changes.

**Comment by HardipinderS** [comment]
can you try now, I think I made pull request
